const en = {

  workDay: "Work Day",

reports: "Reports",

dailyReport: "Daily Report",

weeklyReport: "Weekly Report",

monthlyReport: "Monthly Report",

yearlyReport: "Yearly Report",

boxOfficeEgypt: "🎬 BoxOffice Egypt",

movieRanking: "🏆 Movie Ranking",

cinemaRanking: "🏢 Cinema Ranking",

totalRevenue: "💰 Total Revenue",

totalTickets: "🎟️ Total Tickets",

noData: "No data available.",

backToReports: "Back to Reports",

totalCinemas: "🏢 Total Cinemas",

print: "Print",

pdf: "PDF",

excel: "Excel",

whatsApp: "WhatsApp",

copy: "Copy",

enterRevenue: "Enter Revenue",

selectMovie: "Select Movie",

selectVersion: "Select Version",

addMovie: "Add Movie",

save: "Save",

delete: "Delete",

confirmDeleteMovie: "Do you want to delete this movie from the work day?",

selectMovieFirst: "Please select a movie before entering data.",

duplicateMovie: "The same movie with the same version has been entered more than once.",

enterAtLeastOneMovie: "Please enter at least one movie.",

savedSuccessfully: "✅ Saved successfully",

share: "Share",

backToReports: "Back to Reports",

noData: "No Data",

workDay: "Work Day",

status: "Status",

open: "Open",

closed: "Closed",

closeWorkDay: "Close Work Day",

reopenWorkDay: "Reopen Work Day",

dataEntered: "Completed",

notEntered: "Not Entered",

manageCinema: "Manage Cinema",

back: "Back",

generatedBy: "Generated by BoxOffice Egypt",
};

export default en;