const en = {

  workDay: "Work Day",

reports: "Reports",

dailyReport: "Daily Report",

weeklyReport: "Weekly Report",

monthlyReport: "Monthly Report",

yearlyReport: "Yearly Report",

boxOfficeEgypt: "🎬 BoxOffice Egypt",

movieRanking: "🏆 Movie Ranking",

cinemaRanking: "🏢 Cinema Ranking",

totalRevenue: "💰 Total Revenue",

totalTickets: "🎟️ Total Tickets",

totalCinemas: "🏢 Total Cinemas",

print: "Print",

pdf: "PDF",

excel: "Excel",

whatsApp: "WhatsApp",

copy: "Copy",

share: "Share",

backToReports: "Back to Reports",

noData: "No Data",

generatedBy: "Generated by BoxOffice Egypt",
};

export default en;